### ISSUE TITLE
I couldn't run the code (need help)

### ISSUE THREAD

**Issue by Zitagcc** [hpc/mpimemu#7] opened 2018-06-14 15:11 UTC
I tried to follow the Readme in order to run the code, but when I try to launch ./src/mpimemu-run, I get the following error 

paste.debian.net/1029241/

Best regards.

**Comment by samuelkgutierrez** [comment] 2018-06-14 16:11
Hi,

What kind of system are you running on?
Did the code build successfully?

Thank you

**Comment by samuelkgutierrez** [comment] 2018-06-14 16:22
**Edit**: Please see latest comment.

For what it is worth, I couldn't reproduce this error on my system (Ubuntu Xenial) using the current mpimemu master head. I did have to install libswitch-perl (sudo apt-get install libswitch-perl), though.

This is a very strange error. Can you please try again in a clean (i.e., new) shell environment?

**Comment by samuelkgutierrez** [comment] 2018-06-14 16:31
Oh, I see! You have attached a link to the error (I thought this was the *actual* error). Silly me.

Okay. Can you please send me the output of the following command:
```
cat /proc/self/status
```

**Comment by Zitagcc** [comment] 2018-06-15 11:59
I'm working on ubuntu 18.04TLS.

Please find the output of the command through this [link](http://paste.debian.net/1029370/).

**Comment by samuelkgutierrez** [comment] 2018-06-15 15:36
Thank you.

I think this was the problem (See: 3a8219ce7d62ed7794273e51611382181cde1af8).

Can you pull the latest version of the code and try again?

Thank you,

Sam

**Comment by Zitagcc** [comment] 2018-06-15 18:45
Thank you, it seems that it goes better but the issue remains. 

Please take a look at the [output](http://paste.debian.net/1029424/).

**Comment by samuelkgutierrez** [comment] 2018-06-15 23:06
Okay, good. I'm glad that problem is now fixed.

May I see the output from the following command:

```
env | grep MPIMEMU
```

**Comment by samuelkgutierrez** [comment] 2018-06-15 23:40
I think I see what's happening. It appears as if there is a line break in
```
MPIMEMU_BIN_PATH: /usr/local/bin/mpimemu
```
This is causing the mpimemu binary to be run without any arguments and then the following, namely:
```
-t
```
is being interpreted as a command.

This is supported by the following output:
```
# running: mpirun -n 1 /usr/local/bin/mpimemu
 -t 2 -s 10 -w
###
### mpimemu: 1.2-alpha
### date-time: 20180615-113310
### mpi version: 3.1
### numpe: 1
### num nodes: 1
### ppn: 1
### communication workload enabled: no
### samples/second: 10
### sampling duration (seconds): 10
```
Notice that your runtime arguments are being ignored.

**Comment by samuelkgutierrez** [comment] 2018-06-15 23:45
For reference, please see the following expected output.

```
# running: mpirun -n 1 /home/samuel/devel/mpimemu/src/mpimemu -t 2 -s 10 -w
###
### mpimemu: 1.2-alpha
### date-time: 20180615-174433
### mpi version: 3.1
### numpe: 1
### num nodes: 1
### ppn: 1
### communication workload enabled: yes
### samples/second: 10
### sampling duration (seconds): 2
###
```

**Comment by Zitagcc** [comment] 2018-06-16 06:40
Thank you a lot, it works now. 

Toufik.B

**Closed as completed** 2018-06-16 08:11 UTC

**Comment by samuelkgutierrez** [comment] 2018-06-16 13:35
You're welcome---glad to hear it.
